[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bump_seed_canonicalization = "2aUjVCUm1awbmv8aZHZZ2gUzDxoRzFfrFc9CuubDqycn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -r tsx -p ./tsconfig.json -t 1000000 tests/*.ts"
